Repository woowa-techcamp-2020/market-11, pull requests merged in 2020-07, with the labels that each got.

#1 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE.md
Labels: documentation

#3 docs : 풀 리퀘스트 템플릿 작성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#4 docs: 컨트리뷰션 가이드 추가
  CONTRIBUTING.md
Labels: documentation

#5 docs: 풀 리퀘스트 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#6 docs: 프로젝트 문서 정리
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#20 feat: 회원가입 페이지 마크업 #9
  frontend/public/css/reset.css
  frontend/public/css/style.css
  frontend/views/sign-up.html
Labels: CSS, HTML, frontend

#21 feat: 가입완료 페이지 마크업 #8
  frontend/public/assets/arr-blue.png
  frontend/public/css/style.css
  frontend/views/sign-up-complete.html
Labels: CSS, HTML, frontend

#22 feat: 데이터베이스 구현 #19
  .gitignore
  backend/package-lock.json
  backend/package.json
  backend/router/main.js
  backend/server.js
Labels: backend, database, express

#23 feat: 체크박스 선택시 이미지 바꾸기
  frontend/public/css/style.css
Labels: CSS, HTML, frontend

#24 refactor: 서버와 라우터 기본 구조 작성
  package-lock.json
  package.json
  router/main.js
  server.js
Labels: backend

#25 feat: 회원가입, 가입완료 페이지 마크업 추가
  public/assets/arr-blue.png
  public/css/reset.css
  public/css/style.css
  views/sign-up-complete.html
  views/sign-up.html
Labels: CSS, HTML, frontend

#26 feat: 백엔드 기본 구조 추가
  .gitignore
  package-lock.json
  package.json
  router/main.js
  server.js
Labels: backend

#29 fix: safari와 firefox에서도 동일한 뷰를 지원하도록 수정 #27
  public/css/style.css
Labels: CSS, frontend

#30 feat: 회원가입 페이지 약관 체크 기능 구현 #17
  public/js/index.js
  views/sign-up.html
Labels: JS, frontend

#31 feat: html 마크업 pug 템플릿으로 변환
  router/router.js
  router/utils.js
  server.js
  views/sign-up-complete.pug
  views/sign-up.html
  views/sign-up.pug
Labels: HTML, backend

#32 feat: 회원가입 기능 구현 #16
  router/router.js
  router/utils.js
Labels: backend, database, express

#33 feat: 회원가입 페이지 선택 정보 주소 기능 구현 #14
  public/css/style.css
  public/js/index.js
  views/sign-up.html
  views/sign-up.pug
Labels: JS, frontend

#34 feature: 회원가입 페이지 입력 조건 기능 구현 #12
  public/css/style.css
  public/js/validation.js
  router/utils.js
  views/sign-up.pug
Labels: CSS, JS, frontend

#35 feat: 회원가입 페이지 가입 완료 버튼 기능 구현 #18
  public/css/style.css
  public/js/validation.js
  views/sign-up.pug
Labels: JS, frontend

#36 feat: 회원가입 페이지 이메일 & 휴대폰 인증 기능 구현 #13
  public/css/style.css
  public/js/email.js
  public/js/find-address.js
  public/js/index.js
  public/js/option-info.js
  public/js/phone-auth.js
  public/js/terms.js
  views/sign-up.pug
Labels: JS, frontend

#37 feat: 로그인 페이지 마크업 #10
  public/css/style.css
  router/router.js
  views/login.pug
Labels: CSS, frontend

#38 feat: 메인 페이지 마크업 #7
  public/css/style.css
  router/router.js
  views/login.pug
  views/main.pug
Labels: CSS, frontend

#39 feat: 로그인 기능 구현 resolve #15
  router/router.js
  router/utils.js
  views/login.pug
Labels: backend, express

#40 refactor: updateCheckBox 함수 리팩토링
  public/js/terms.js
Labels: JS, frontend

#41 feat: 로그인 성공 시 세션 사용 기능 추가 #15
  package-lock.json
  router/router.js
  router/utils.js
  server.js
Labels: backend, express

#42 feat: 로그인 페이지 프론트 기능 구현 #11
  public/css/style.css
  public/js/login-validation.js
  router/router.js
  router/utils.js
  user.db
  views/login.html
  views/login.pug
  views/main.pug
Labels: JS, frontend

#43 feat: 회원가입 성공시 회원가입 페이지로 이동 #18
  public/js/phone-auth.js
  router/utils.js
  views/sign-up-complete.pug
  views/sign-up.pug
Labels: backend, frontend

#44 feat: 로그인 실패 시 에러메시지 노출 #11
  router/utils.js
  views/login.pug
Labels: backend, frontend

#46 refactor: email 관련 함수 리팩토링
  public/css/style.css
  public/js/email.js
Labels: JS, frontend

#49 feat: 회원가입 폼 입력할때 아이디 중복 체크 #12
  public/js/validation.js
  router/router.js
  router/utils.js
Labels: JS, backend, frontend

#47 fix: 주소 및 상세 주소 입력 부분 클릭 시 우편번호 찾기 팝업 창 뜨는 에러 수정
  public/js/find-address.js
  public/js/option-info.js
Labels: JS, frontend

#48 fix: 휴대폰 인증 부분 오류 수정 #45
  public/js/phone-auth.js
Labels: JS, frontend

#50 fix: 로그인 페이지 회원가입 링크 추가
  views/login.pug
Labels: frontend

#52 fix: 아이디 중복체크 프로미스 문제 해결
  public/js/validation.js
Labels: JS, frontend

#53 feat: 핸드폰 인증 완료 시 버튼 이름 변경 #13
  public/js/phone-auth.js
Labels: JS, frontend

#54 fix: 타이머가 중복 실행되는 문제 해결 #51
  public/js/phone-auth.js
Labels: JS, frontend

#55 fix: 핸드폰 인증안했을때, 가입약관 동의 안했을때 안내창 띄우기
  public/js/validation.js
Labels: JS, frontend
